### ISSUE TITLE
Add ReactJS Boilerplate

### ISSUE THREAD

**Issue by mykartadmin** [mykartadmin/TailwindReactBoilerplate#1]

**Comment by sahiltuli31** [comment]
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root')
);

**Comment by Shuklajiii** [comment]
@mykartadmin  I fixed this issue #5

**Comment by mykartadmin** [comment]
LGTM, Great @Shuklajiii
